#!/usr/bin/env bash
# Usage: codehouse readme LIBRARY_NAME
# Summary: Open library's README file

set -e

error() {
    echo "CODEHOUSE: $1" >&2
    exit 1
}

[ -z "$1" ] && error "must specify a library name"

exec codehouse-open $1 readme
