#!/usr/bin/env bash
set -e

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

libexec_path="$(abs_dirname "$0")"
export _CODEHOUSE_ROOT="$(abs_dirname "$libexec_path")"
export PATH="${libexec_path}:$PATH"

if [ -z "$CODEHOUSE_SRC_ROOT" ]; then
  CODEHOUSE_SRC_ROOT="$HOME/.codehouse-src"
else
  CODEHOUSE_SRC_ROOT="${CODEHOUSE_SRC_ROOT%/}"
fi
export CODEHOUSE_SRC_ROOT

command="$1"
case "$command" in
"" | "-h" | "--help" )
  exec codehouse-help
  ;;
* )
  command_path="$(command -v "codehouse-$command" || true)"
  if [ ! -x "$command_path" ]; then
    echo "codehouse: no such command \`$command'" >&2
    exit 1
  fi

  shift
  exec "$command_path" "$@"
  ;;
esac
