#!/usr/bin/env bash
set -e

error() {
    echo "VL: $1" >&2
    exit 1
}

[ ! -d "$VL_SRC_ROOT" ] && error "cannot find directory \`$VL_SRC_ROOT'"

[ -z "$1" ] && error "must specify a library to open"

if [ -z "$EDITOR" ]; then
    _VL_EDITOR="vim"
else
    _VL_EDITOR="$EDITOR"
fi

lib_name=$(ls $VL_SRC_ROOT | grep -i $1 | head -1)
[ -z "$lib_name" ] && error "no library found matching the name \`$1'"

lib_path="$VL_SRC_ROOT/$lib_name"
target="$lib_path"

if [ ! -z "$2" ]; then
    if [ "$2" = "readme" ]; then
        readme_name=$(ls $lib_path | grep -i readme | head -1)
        target="$lib_path/$readme_name"
    elif [ ! -e "$lib_path/$2" ]; then
        error "invalid file or path \`$2'"
    else
        target="$target/$2"
    fi
fi

$_VL_EDITOR $target
